package System;

/**
 * Represents the method that will handle an event.
 *
 * @author Halofreak1990
 * @param <T>
 * The type of the event data generated by the event.
 */
public interface EventHandler<T>
{
	/**
	 * 
	 * @param sender
	 * The source of the event.
	 * 
	 * @param e
	 * An {@link System.EventArgs} that contains the event data.
	 */
	void Invoke(Object sender, T e);
}

